# Builds and pushes frontend to gh-pages branch
# Pushes backend to server branch

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pushes frontend code to gh-pages branch
  client-integration:
    name: integrate-client
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # building the website
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: build site
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
          echo "v3.samuelp.ing" > out/CNAME
          echo "# Hi!" > out/README.md
          echo "You're currently looking at the build artifacts of my website. To check out the code, switch over to my website's [main repository!](https://github.com/samuel-ping/samuelp.ing)!" >> out/README.md
          echo "#### Note - This message was automatically generated." >> out/README.md
        working-directory: ./

      - name: push build artifacts to self
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
